M48
; DRILL file {KiCad (6.0.9-0)} date Friday, January 13, 2023 at 03:28:54 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-13T15:28:54-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,12,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
%
G90
G05
T1
X3.153Y-5.2711
X3.153Y-5.5878
X3.3498Y-5.2711
X3.3498Y-5.5878
T2
X3.2262Y-4.7537
X3.3463Y-2.6128
T3
X2.8512Y-5.7083
X7.3062Y-5.7083
T0
M30
